trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJava@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

- script: java -version
  displayName: 'Show Java version'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'  # Important: Use the Java path set by UseJava@1
    jdkDirectory: $(JAVA_HOME)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
